# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vector_db_pb2 as vector__db__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vector_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorDBServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchKnowledge = channel.unary_unary(
                '/vector_db.VectorDBService/SearchKnowledge',
                request_serializer=vector__db__pb2.SearchRequest.SerializeToString,
                response_deserializer=vector__db__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.AppendKnowledge = channel.unary_unary(
                '/vector_db.VectorDBService/AppendKnowledge',
                request_serializer=vector__db__pb2.AppendRequest.SerializeToString,
                response_deserializer=vector__db__pb2.AppendResponse.FromString,
                _registered_method=True)


class VectorDBServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchKnowledge(self, request, context):
        """搜尋知識點
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendKnowledge(self, request, context):
        """新增知識點
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDBServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKnowledge,
                    request_deserializer=vector__db__pb2.SearchRequest.FromString,
                    response_serializer=vector__db__pb2.SearchResponse.SerializeToString,
            ),
            'AppendKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendKnowledge,
                    request_deserializer=vector__db__pb2.AppendRequest.FromString,
                    response_serializer=vector__db__pb2.AppendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vector_db.VectorDBService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vector_db.VectorDBService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorDBService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vector_db.VectorDBService/SearchKnowledge',
            vector__db__pb2.SearchRequest.SerializeToString,
            vector__db__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vector_db.VectorDBService/AppendKnowledge',
            vector__db__pb2.AppendRequest.SerializeToString,
            vector__db__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
