class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  static const _localizedValues = {
    'en': {
      'api_lang': 'English',
      'age_invalid':'Age is not valid',
      'bluetooth': 'Blutooth',
      'loginOrSignUp': 'Login / Sign up',
      'logout': 'Logout',
      'loginFailed': 'Login Failed',
      'incorrectAcOrPw': 'Login Failed',
      'confirm': 'confirm',
      'connect_bluetooth': 'Connect to eye testing robot',
      'createAccount': 'Create Account',
      'createAccountFailed': 'Create Account Failed',
      'unexpectedErr': 'Unexpected error occured',
      'duplicatedAc': 'The username or email has already used',
      'disconnect': 'Disconnect',
      'usernameOrEmail': 'Email or Username',
      'update_profile': 'Update user profile',
      'update_profile_failed': 'Failed to update user profile',
      'update_profile_success': 'Update user profile successfully',
      'password': 'Password',
      'measure_corr': 'Measure Corrected Vision?',
      'measure_l': 'Measure left eye',
      'measure_r': 'Measure right eye',
      'measure_cl': 'Measure left eye with glasses',
      'measure_cr': 'Measure right eye with glasses',
      'short_password': 'Password is less than 8 words',
      'email': 'Email',
      'email_invalid': 'Email is invalid',
      'username': 'Username',
      'require_username': 'Username is quired',
      'require_username_or_email': 'Username or Eamil is quired',
      'refresh_bluetooth': 'Refresh bluetooth devices',
      'refresh_records': 'Refresh eye test records',
      'require_password': 'Please enter password',
      'require_email': 'Please enter Email',
      'require_age' : 'Please enter age',
      'age': 'Age',
      'gender': 'Gender',
      'job': 'Job',
      'record': 'Vision Records',
      'remote': 'Remote',
      'settings': 'Settings',
      'start_measure': 'Start measurement',
      'select_diopler': 'Select glasses\' diopler',
      'language': 'Language',
      'fontSize': 'Font Size',
      'search_date': 'Search Date',
      'input_msg': 'Input message here...',
      'input_date_hint': 'Enter date keyword (yyyy-mm-dd)',
      'date': 'Date',
      'uncorrected_left': 'Left Eye',
      'uncorrected_right': 'Right Eye',
      'corrected_left': 'Corrected (L)',
      'corrected_right': 'Corrected (R)',
      'vision': 'Vision ',
      'power': 'Power ',
      'optional': 'Optional',
      'wait_response': 'Waiting response...',
    },
    'zh': {
      'api_lang': 'STT for course',
      'age_invalid':'年齡不能給你這樣搞',
      'bluetooth': '藍芽',
      'loginOrSignUp': '登入 / 註冊',
      'logout': '登出',
      'loginFailed': '登入失敗',
      'incorrectAcOrPw': '帳號或密碼錯誤',
      'confirm': '確定',
      'connect_bluetooth': '連線到檢測機器人',
      'createAccount': '建立帳號',
      'createAccountFailed': '帳號建立失敗',
      'unexpectedErr': '發生未知錯誤',
      'duplicatedAc': '使用者名稱或 Email 已存在',
      'disconnect': '中斷連線',
      'usernameOrEmail': 'Email 或使用者名稱',
      'update_profile': '更新使用者資料',
      'update_profile_failed': '更新使用者資料失敗',
      'update_profile_success': '已更新使用者資料',
      'password': '密碼',
      'measure_corr': '是否測量矯正視力',
      'measure_l': '測量左眼裸視視力',
      'measure_r': '測量右眼裸視視力',
      'measure_cl': '測量左眼矯正視力',
      'measure_cr': '測量右眼矯正視力',
      'short_password': '密碼短於8個字',
      'email': 'Email',
      'email_invalid': 'Email不正確',
      'username': '使用者名稱',
      'require_username': '需要使用者名稱',
      'require_username_or_email': '需要使用者名稱 或 Eamil',
      'refresh_bluetooth': '重新搜尋藍芽裝置',
      'refresh_records': '重整視力紀錄',
      'require_password': '請輸入密碼',
      'require_email': '請輸入 Email',
      'require_age' : '請輸入年紀',
      'age': '年齡',
      'gender': '性別',
      'job': '職業',
      'record': '視力紀錄',
      'remote': '遙控',
      'settings': '設定',
      'start_measure': '開始測量',
      'select_diopler': '選擇眼鏡度數',
      'language': '語言',
      'fontSize': '字體大小',
      'search_date': '搜尋日期',
      'input_msg': '輸入訊息...',
      'input_date_hint': '輸入日期關鍵字 (yyyy-mm-dd)',
      'date': '日期',
      'uncorrected_left': '左眼',
      'uncorrected_right': '右眼',
      'corrected_left': '左眼矯正',
      'corrected_right': '右眼矯正',
      'vision': '視力 ',
      'power': '度數 ',
      'optional': '可選',
      'wait_response': '正在輸入...',
    },
    'tw': {
      // TODO: this is not valid api_lang
      'api_lang': 'TA Phoneme',
      'age_invalid':'年齡不能給你這樣搞',
      'bluetooth': '藍芽',
      'loginOrSignUp': '登入 / 註冊',
      'logout': '登出',
      'loginFailed': '登入失敗',
      'incorrectAcOrPw': '帳號或密碼錯誤',
      'confirm': '確定',
      'connect_bluetooth': '連線到檢測機器人',
      'createAccount': '建立帳號',
      'createAccountFailed': '帳號建立失敗',
      'unexpectedErr': '發生未知錯誤',
      'duplicatedAc': '使用者名稱或 Email 已存在',
      'disconnect': '中斷連線',
      'usernameOrEmail': 'Email 或使用者名稱',
      'update_profile': '更新使用者資料',
      'update_profile_failed': '更新使用者資料失敗',
      'update_profile_success': '已更新使用者資料',
      'password': '密碼',
      'measure_corr': '是否測量矯正視力',
      'measure_l': '測量左眼裸視視力',
      'measure_r': '測量右眼裸視視力',
      'measure_cl': '測量左眼矯正視力',
      'measure_cr': '測量右眼矯正視力',
      'short_password': '密碼短於8個字',
      'email': 'Email',
      'email_invalid': 'Email不正確',
      'username': '使用者名稱',
      'require_username': '需要使用者名稱',
      'require_username_or_email': '需要使用者名稱 或 Eamil',
      'refresh_bluetooth': '重新搜尋藍芽裝置',
      'refresh_records': '重整視力紀錄',
      'require_password': '請輸入密碼',
      'require_email': '請輸入 Email',
      'require_age' : '請輸入年紀',
      'age': '年齡',
      'gender': '性別',
      'job': '職業',
      'record': '視力紀錄',
      'remote': '遙控',
      'settings': '設定',
      'start_measure': '開始測量',
      'select_diopler': '選擇眼鏡度數',
      'language': '語言',
      'fontSize': '字體大小',
      'search_date': '搜尋日期',
      'input_msg': '輸入訊息...',
      'input_date_hint': '輸入日期關鍵字 (yyyy-mm-dd)',
      'date': '日期',
      'uncorrected_left': '左眼',
      'uncorrected_right': '右眼',
      'corrected_left': '左眼矯正',
      'corrected_right': '右眼矯正',
      'vision': '視力 ',
      'power': '度數 ',
      'optional': '可選',
      'wait_response': '正在輸入...',
    },
    'ja': {
      'api_lang': 'Japanese',
      'age_invalid': '年齢が無効です',
      'bluetooth': 'Bluetooth',
      'loginOrSignUp': 'ログイン / 新規登録',
      'logout': 'ログアウト',
      'loginFailed': 'ログインに失敗しました',
      'incorrectAcOrPw': 'アカウントまたはパスワードが間違っています',
      'confirm': '確認',
      'connect_bluetooth': '視力検査ロボットに接続',
      'createAccount': 'アカウント作成',
      'createAccountFailed': 'アカウント作成に失敗しました',
      'unexpectedErr': '予期しないエラーが発生しました',
      'duplicatedAc': 'ユーザー名またはメールアドレスは既に使用されています',
      'disconnect': '切断',
      'usernameOrEmail': 'ユーザー名またはメールアドレス',
      'update_profile': 'プロフィールを更新',
      'update_profile_failed': 'プロフィールの更新に失敗しました',
      'update_profile_success': 'プロフィールを更新しました',
      'password': 'パスワード',
      'measure_corr': '矯正視力を測定しますか？',
      'measure_l': '左目を測定',
      'measure_r': '右目を測定',
      'measure_cl': '左目（眼鏡あり）を測定',
      'measure_cr': '右目（眼鏡あり）を測定',
      'short_password': 'パスワードは8文字未満です',
      'email': 'メールアドレス',
      'email_invalid': '無効なメールアドレスです',
      'username': 'ユーザー名',
      'require_username': 'ユーザー名を入力してください',
      'require_username_or_email': 'ユーザー名またはメールアドレスを入力してください',
      'refresh_bluetooth': 'Bluetoothデバイスを再検索',
      'refresh_records': '視力記録を更新',
      'require_password': 'パスワードを入力してください',
      'require_email': 'メールアドレスを入力してください',
      'require_age': '年齢を入力してください',
      'age': '年齢',
      'gender': '性別',
      'job': '職業',
      'record': '視力記録',
      'remote': 'リモート',
      'settings': '設定',
      'start_measure': '測定開始',
      'select_diopler': '眼鏡の度数を選択',
      'language': '言語',
      'fontSize': '文字サイズ',
      'search_date': '日付検索',
      'input_msg': 'ここにメッセージを入力...',
      'input_date_hint': '日付キーワードを入力（yyyy-mm-dd）',
      'date': '日付',
      'uncorrected_left': '左目',
      'uncorrected_right': '右目',
      'corrected_left': '矯正済み（左）',
      'corrected_right': '矯正済み（右）',
      'vision': '視力 ',
      'power': '度数 ',
      'optional': '任意',
      'wait_response': '応答待ち...',
    },
  };

  String get(String key) {
    return _localizedValues[locale]?[key] ?? key;
  }
}
