class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  static const _localizedValues = {
    'en': {
      'bluetooth': 'Blutooth',
      'loginOrSignUp': 'Login / Sign up',
      'logout': 'Logout',
      'loginFailed': 'Login Failed',
      'incorrectAcOrPw': 'Login Failed',
      'confirm': 'confirm',
      'connect_bluetooth': 'Connect to eye testing robot',
      'createAccount': 'Create Account',
      'createAccountFailed': 'Create Account Failed',
      'unexpectedErr': 'Unexpected error occured',
      'duplicatedAc': 'The username or email has already used',
      'usernameOrEmail': 'Email or Username',
      'update_profile': 'Update user profile',
      'update_profile_failed': 'Failed to update user profile',
      'update_profile_success': 'Update user profile successfully',
      'password': 'Password',
      'short_password': 'Password is less than 6 words',
      'email': 'Email',
      'email_invalid': 'Email is invalid',
      'username': 'Username',
      'require_username': 'Username is quired',
      'refresh_bluetooth': 'Refresh bluetooth devices',
      'refresh_records': 'Refresh eye test records',
      'age': 'Age',
      'gender': 'Gender',
      'job': 'Job',
      'record': 'Vision Records',
      'remote': 'Remote',
      'settings': 'Settings',
      'language': 'Language',
      'fontSize': 'Font Size',
      'search_date': 'Search Date',
      'input_msg': 'Input message here...',
      'input_date_hint': 'Enter date keyword (yyyy-mm-dd)',
      'date': 'Date',
      'uncorrected_left': 'Left Eye',
      'uncorrected_right': 'Right Eye',
      'corrected_left': 'Corrected (L)',
      'corrected_right': 'Corrected (R)',
      'vision': 'Vision ',
      'power': 'Power ',
      'optional': 'Optional',
      'wait_response': 'Waiting response...',
    },
    'zh': {
      'bluetooth': '藍芽',
      'loginOrSignUp': '登入 / 註冊',
      'logout': '登出',
      'loginFailed': '登入失敗',
      'incorrectAcOrPw': '帳號或密碼錯誤',
      'confirm': '確定',
      'connect_bluetooth': '連線到檢測機器人',
      'createAccount': '建立帳號',
      'createAccountFailed': '帳號建立失敗',
      'unexpectedErr': '發生未知錯誤',
      'duplicatedAc': '使用者名稱或 Email 已存在',
      'usernameOrEmail': 'Email 或使用者名稱',
      'update_profile': '更新使用者資料',
      'update_profile_failed': '更新使用者資料失敗',
      'update_profile_success': '已更新使用者資料',
      'password': '密碼',
      'short_password': '密碼短於6個字',
      'email': 'Email',
      'email_invalid': 'Email不正確',
      'username': '使用者名稱',
      'require_username': '需要使用者名稱',
      'refresh_bluetooth': '重新搜尋藍芽裝置',
      'refresh_records': '重整視力紀錄',
      'age': '年齡',
      'gender': '性別',
      'job': '職業',
      'record': '視力紀錄',
      'remote': '遙控',
      'settings': '設定',
      'language': '語言',
      'fontSize': '字體大小',
      'search_date': '搜尋日期',
      'input_msg': '輸入訊息...',
      'input_date_hint': '輸入日期關鍵字 (yyyy-mm-dd)',
      'date': '日期',
      'uncorrected_left': '左眼',
      'uncorrected_right': '右眼',
      'corrected_left': '左眼矯正',
      'corrected_right': '右眼矯正',
      'vision': '視力 ',
      'power': '度數 ',
      'optional': '可選',
      'wait_response': '正在輸入...',
    },
  };

  String get(String key) {
    return _localizedValues[locale]?[key] ?? key;
  }
}
