# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_db.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'vector_db.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvector_db.proto\x12\tvector_db\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"<\n\x0cSearchResult\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\x12\x12\n\nsimilarity\x18\x03 \x01(\x02\"[\n\x0eSearchResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12(\n\x07results\x18\x03 \x03(\x0b\x32\x17.vector_db.SearchResult\"c\n\rKnowledgeData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fknowledge_point\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\"=\n\rAppendRequest\x12,\n\nknowledges\x18\x01 \x03(\x0b\x32\x18.vector_db.KnowledgeData\"B\n\x0e\x41ppendResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07new_ids\x18\x03 \x03(\t2\xa1\x01\n\x0fVectorDBService\x12\x46\n\x0fSearchKnowledge\x12\x18.vector_db.SearchRequest\x1a\x19.vector_db.SearchResponse\x12\x46\n\x0f\x41ppendKnowledge\x12\x18.vector_db.AppendRequest\x1a\x19.vector_db.AppendResponseB,\n\x19\x63om.example.demo.vectordbB\rVectorDbProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_db_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.example.demo.vectordbB\rVectorDbProtoP\001'
  _globals['_SEARCHREQUEST']._serialized_start=30
  _globals['_SEARCHREQUEST']._serialized_end=75
  _globals['_SEARCHRESULT']._serialized_start=77
  _globals['_SEARCHRESULT']._serialized_end=137
  _globals['_SEARCHRESPONSE']._serialized_start=139
  _globals['_SEARCHRESPONSE']._serialized_end=230
  _globals['_KNOWLEDGEDATA']._serialized_start=232
  _globals['_KNOWLEDGEDATA']._serialized_end=331
  _globals['_APPENDREQUEST']._serialized_start=333
  _globals['_APPENDREQUEST']._serialized_end=394
  _globals['_APPENDRESPONSE']._serialized_start=396
  _globals['_APPENDRESPONSE']._serialized_end=462
  _globals['_VECTORDBSERVICE']._serialized_start=465
  _globals['_VECTORDBSERVICE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
