server:
  port: 8080
#  error:
#    include-message: always
#    include-binding-errors: always
public:
  endpoints:
    - /api/auth/register
    - /api/auth/login
    - /api/auth/verify-email
spring:
  datasource:
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
#logging: #debug
 # level:
  #  org.springframework: DEBUG
   # org.hibernate: DEBUG
    #com.example.demo: DEBUG